[project]
name = "orchestrator"
version = "0.1.0"
description = ""
authors = [
  {name = "David Duran",email = "dadch1404@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ruff (>=0.9.3,<0.10.0)",
    "fastapi (>=0.115.7,<0.116.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "pydantic (>=2.10.6,<3.0.0)",
    "scipy (==1.11.4)",
    "numpy (==1.26.4)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
httpx = "^0.25.0"
pytest-cov = "^4.1.0"

[tool.ruff]
target-version = "py310"
line-length = 88
indent-width = 4

extend-exclude = [
    "__pycache__",
    "dist",
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "B",
    "I",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.poe.tasks]
format = { shell = "ruff format && ruff check --fix" }
