name: Security Report

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  security_checks:
    runs-on: ubuntu-latest
    name: PyCharm Security Scan

    steps:
      - uses: actions/checkout@v2

      - uses: tonybaloney/pycharm-security@1.25.1
        with:
          path: orchestrator/
          fail_on_warnings: "no"
